### ISSUE TITLE
fix registration

### ISSUE THREAD

**Issue by MicahDadson** [jeremymeadows/Mentality#22]
I get a sql connector error when trying to register.

**Comment by jeremymeadows** [comment]
can you reproduce it? it worked for me

**Comment by MicahDadson** [comment]
<img width="714" alt="Screen Shot 2020-04-29 at 10 32 53 PM" src="https://user-images.githubusercontent.com/44760902/80669199-693c9a80-8a69-11ea-9bde-01c865b939c1.png">
<img width="129" alt="Screen Shot 2020-04-29 at 10 32 59 PM" src="https://user-images.githubusercontent.com/44760902/80669208-7063a880-8a69-11ea-8ac7-4b649762fbd0.png">

Yeah once I register it says "bad connection" and doesn't save to the database

**Comment by MicahDadson** [comment]
and the only part of the code that I changed is to turn debug to false.

**Comment by jeremymeadows** [comment]
All that debug function does is enter in login cause I got tired of doing it manually haha. I’ll see if I can make it show the same error

**Comment by jeremymeadows** [comment]
so apparently Java and MySQL do different things with unsigned ints (they don't even exist in Java), so I just had to tweak how Java stored them so that they looked right in the SQL update.
